spring:
  application:
    name: config-server
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/seremweng/em-configurations-strore.git
server:
  port: 9100
#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9101/eureka



